---
abstract: 'routines for manipulating stashes'
author:
  - 'Jesse Luehrs <doy at tozt dot net>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101241'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Stash-Manip
recommends: {}
requires:
  Scalar::Util: 0
version: 0.01
